/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CustomClock {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
    'setText': (first: string, middle: string, last: string) => Promise<void>;
  }
  interface PropReflect {
    'message': string;
  }
}

declare global {


  interface HTMLCustomClockElement extends Components.CustomClock, HTMLStencilElement {}
  var HTMLCustomClockElement: {
    prototype: HTMLCustomClockElement;
    new (): HTMLCustomClockElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPropReflectElement extends Components.PropReflect, HTMLStencilElement {}
  var HTMLPropReflectElement: {
    prototype: HTMLPropReflectElement;
    new (): HTMLPropReflectElement;
  };
  interface HTMLElementTagNameMap {
    'custom-clock': HTMLCustomClockElement;
    'my-component': HTMLMyComponentElement;
    'prop-reflect': HTMLPropReflectElement;
  }
}

declare namespace LocalJSX {
  interface CustomClock extends JSXBase.HTMLAttributes<HTMLCustomClockElement> {}
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface PropReflect extends JSXBase.HTMLAttributes<HTMLPropReflectElement> {
    'message'?: string;
  }

  interface IntrinsicElements {
    'custom-clock': CustomClock;
    'my-component': MyComponent;
    'prop-reflect': PropReflect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


